language: node_js
node_js:
- 10
before_install:
- npm install -g npm@latest
- npm install -g firebase-tools
script:
- 
deploy:
  provider: firebase
  token:
    secure: l/B/kJD0MJt3/KBYw5zJ7HYNV0TeCtF8B4qj+mWGMeNANsCfKblmOtRJw9BEuBeUHfvt6/czMn1Onql77kq+QDZjKCYOneG4aAQfY0FuwI/5xEdq+soT0OFZFeJ1+5FDInB7JxcHi2Vg7NZaSsQd/pIvn9ybLILGKi3CJNuFrIPv0544I4InzVt4RKDh6pnOzjxHgcmavNYFXbCypIXsIjjpZc1YfCLsjT4k0u0fEk8ohOEGb+1ANAKoKW09thaEihr0+d4mrFGTmrqBBYo/ODm2DzdTHKlIqo7yBf05NLKr7S+WNLqgBkkt5nOiZyXnTtLQdIUc4WdiK9gMTbrakz6JuriM6HSV7ZhvwgICtquc05iqHgNoFM0tiUPBzrLATMZVAxMSkr9yED1h+He4D8J3WnScmeHrqsPzNuEUGZrASdcqzsrac4ofDqT2rP99aj9UqSr0EFjtori64JeUJhkcGTFPd52sqyl+XviSmA3RsPTuWIWZIhKAe1+sZQ9RkkD4L+4J1PZGZGFLYHKf03gxxb0LK4Ux8VdMFGA+5QdkJTA5uCCDjzVP5NyXFce2IP+6DHHhODNOwRjbhquc7kG5RMEbSGG/HOANsz8BewczEEjwKFVvndoQAOmLT0crPu2eec03DqGX42hdCmg8zy+T8uJ2sqYo1udDVh4DqiU=