language: node_js
node_js:
- 10
before_install:
- npm install -g npm@latest
- npm install -g firebase-tools
script:
- 
deploy:
  provider: firebase
  token:
    secure: "l/B/kJD0MJt3/KBYw5zJ7HYNV0TeCtF8B4qj+mWGMeNANsCfKblmOtRJw9BEuBeUHfvt6/czMn1Onql77kq+QDZjKCYOneG4aAQfY0FuwI/5xEdq+soT0OFZFeJ1+5FDInB7JxcHi2Vg7NZaSsQd/pIvn9ybLILGKi3CJNuFrIPv0544I4InzVt4RKDh6pnOzjxHgcmavNYFXbCypIXsIjjpZc1YfCLsjT4k0u0fEk8ohOEGb+1ANAKoKW09thaEihr0+d4mrFGTmrqBBYo/ODm2DzdTHKlIqo7yBf05NLKr7S+WNLqgBkkt5nOiZyXnTtLQdIUc4WdiK9gMTbrakz6JuriM6HSV7ZhvwgICtquc05iqHgNoFM0tiUPBzrLATMZVAxMSkr9yED1h+He4D8J3WnScmeHrqsPzNuEUGZrASdcqzsrac4ofDqT2rP99aj9UqSr0EFjtori64JeUJhkcGTFPd52sqyl+XviSmA3RsPTuWIWZIhKAe1+sZQ9RkkD4L+4J1PZGZGFLYHKf03gxxb0LK4Ux8VdMFGA+5QdkJTA5uCCDjzVP5NyXFce2IP+6DHHhODNOwRjbhquc7kG5RMEbSGG/HOANsz8BewczEEjwKFVvndoQAOmLT0crPu2eec03DqGX42hdCmg8zy+T8uJ2sqYo1udDVh4DqiU="
# env:
#   global:
#     secure: evYjOQ4l8n4eMBCJ4+HKsuxnF2HiVPPPBWLrj7gDCa9mRp0Ij4GSunbqsWH81p0d4To+w0tIKYjE9SGufRImDX+YQARgF1mTCgDuW0HoeaHCrx8Z6BYK0TfRSaYSCWxo9EYg4l23hPlxLxua3wrwjjY8I0qfy3BY9CMKB/lTOgPG8MQ+rhSLISX42hMSpDde1xQ62URwF6DrCvFESzzr4STyzA0P0fI+4G5jTscR7ZMZPwYw2NlYinpPLkQd/R1en+UV+AKyxLyc/mlwuVyJp5bLkJVJw1BjZQ4QBGohFPZGpWjkvfQRt+0qAzj85zQ7konO36cnscRbVZvHTGWV7XxqiljzW+FT8bToh0SM2SXz4NVqSs6ZSrPF+yCWB+wqUhuRpd2SyQnXUI4ekueMeYPrve2yzKvgDIjP5mQK9vvYsavFNAkJHQSU7aExf037GpP9xd8OduPJf4Cn2O1Q+mHhIxDGSXhUgvdlpQEQiHTrj7ciSPhWKu7TaOqa7BPL7v3K58GdN7/VnXz3oJUF0CFIQrTmV+bnSv427AJDm9rKL+DMzezpEycgOG0m3Ww10PMmxGq/zPE47DAk4cHPWp2FtPnojtgB9NFcLePsVAJT3TceZPoVG0xjYmN45wXHeCV2VhSccbaIlh17w9t18ZouH+TeMQZj/LLGDcMyUnI=
